# Generated by Django 2.2.7 on 2021-03-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_choice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
