# Generated by Django 2.2.7 on 2021-03-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_choice_is_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_Choice',
            new_name='Choice',
        ),
    ]
