# Generated by Django 3.1.7 on 2021-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210318_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
