# Generated by Django 3.1.7 on 2021-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210328_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='num_of_modules',
        ),
    ]
