# Generated by Django 3.1.7 on 2021-04-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_course_num_of_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='questions.course')),
                ('module', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='questions.module')),
                ('questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
